### ISSUE TITLE
cudnn 7

### ISSUE THREAD

**Issue by bafonso** [zeruniverse/fast-artistic-videos#10]
Is it possible to recompile this for cudnn 7? I could attempt to do it if I could get some pointers.

**Comment by zeruniverse** [comment]
Can you install distro? I believe this comes with all setups for torch.

I will not suggest to compile CUDNN or CUDA. And I do believe there should be torch release supporting the newest CUDA or CUDNN even though it’s no longer under development.

**Comment by bafonso** [comment]
The problem is that the default cudnn bindings are for cudnn5. But you can get the R7 branch and then it compiles fine for cudnn 7. I'm not finding it much faster than my cpu, is that normal? :)

**Comment by zeruniverse** [comment]
Oh, I was about to tell you this: https://github.com/torch/torch7/issues/1133#issuecomment-376038963

So generating optical flow is pretty slow and it's on CPU. but for applying styles you should see improvements on GPU. (run nvidia-smi to see if GPU is actually used)

**Comment by bafonso** [comment]
Thanks. Is there a way to compute optical flow on the GPU? Would it be faster? :)

**Comment by zeruniverse** [comment]
I actually tried [OpenACC](https://www.openacc.org/) for deepflow and it does not work well. The reason is there're very limited parallelizations you can do given your image is not so large and the optimization steps shoud be run epoch by epoch which are serial. I would suggest using OpenMP to parallelize the optical flow algorithm if it hasn't been multi-threading.
